kind: ClusterConfig
metadata:
  name: k0s
  namespace: kube-system
spec:
  api:
    address: 192.168.1.12
    ca:
      certificatesExpireAfter: 8760h0m0s
      expiresAfter: 87600h0m0s
    k0sApiPort: 9443
    port: 6443
  controllerManager: {}
# I decided to move Argo managed cus don't want to restart k0s every times I made config changes
  extensions:
    helm:
      concurrencyLevel: 5
      repositories:
        - name: cilium
          url: https://helm.cilium.io/
      charts:
        - name: cilium
          chartname: cilium/cilium
          version: "1.18.0"
          namespace: kube-system
          values: |
            kubeProxyReplacement: true
            k8sServiceHost: 192.168.1.12
            k8sServicePort: 6443
            l2announcements:
              enabled: true
            k8sClientRateLimit:
              qps: 10
              burst: 20
            operator:
              replicas: 1
  installConfig:
    users:
      etcdUser: etcd
      kineUser: kube-apiserver
      konnectivityUser: konnectivity-server
      kubeAPIserverUser: kube-apiserver
      kubeSchedulerUser: kube-scheduler
  konnectivity:
    adminPort: 8133
    agentPort: 8132
  network:
    clusterDomain: hkocluster.local
    dualStack:
      enabled: false
    # Completely disable kube-proxy to let Cilium handle LB and proxying
    kubeProxy:
      disabled: true
    nodeLocalLoadBalancing:
      enabled: false
      envoyProxy:
        apiServerBindPort: 7443
        konnectivityServerBindPort: 7132
      type: EnvoyProxy
    podCIDR: 10.244.0.0/16
    # Change the network provider to custom
    # If you want/have another cluster -> podCIDR & service CIDR should carefully set
    provider: custom
    serviceCIDR: 10.96.0.0/12
  scheduler: {}
  storage:
    etcd:
      ca:
        certificatesExpireAfter: 8760h0m0s
        expiresAfter: 87600h0m0s
      peerAddress: 192.168.1.12
    type: etcd
  telemetry:
    enabled: false
